version: '3'

services:
  web:
    build: .
    container_name: web_personalstammblatt
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:8080"

  database:
    image: mariadb:10.4
    container_name: db_personalstammblatt
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DB_NAME}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
